import 'dart:ui';

abstract class Strings {
 String  PleaseWait;
  String appName;
  String langPage;
  String arabicLang;
  String englishLang;
  String languages;
  String languagesDes;
  String alertExitTitle;
  String exitApp;
  String home;
  String KuwaitiLivestock;
  String schedule;
  String profile;
  String product;
  String services;
  String serviceNoti;
  String servicesDetails;
  String selectServices;
  String contract;
  String notification;
  String news;
  String municipalCouncils;
  String theMedia;
  String about;
  String contactUs;
  String complaintsAndSuggestions;
  String logout;
  String login;
  String userName;
  String fillDataError;
  String errorUserName;
  String userPassword;
  String errorPassword;
  String signIn;
  String signInWithFacebook;
  String dontHaveAccount ;
  String register ;
  String alreadyHaveAccount ;
  String signUp;
  String firstUserName;
  String lastUserName;
  String phoneNum ;
  String massagesDesc ;
  String email ;
  String userRePassword;
  String forgetPassword;
  String passwordLess6;
  String errorMatchPassword;
  String errorPhone ;
  String phoneNumValid;
  String alertLogout;
  String exitapp;
  String emailUsed;
   String send;
   String FirstName;
  String secondname;
   String photoAlbum;
  String videoAlbum;
  String MunicipalCouncils;
  String CurrentCouncils;
  String PreviousCouncils;
  String MunicipalMembers;
  String employees;
  String yes;
  String no;
  String ReadMore;
  String search;
  String enterusername;
  String enterpassword;
   String userEmail;
  String welcome;
  String title;
  String ComplaintTitle;
  String yourMsg;
  String yourProblem;
  String yourNote;
  String addAppointment;
  String uploadImage;
  String location;
  String locationClient;
  String Appointment;
  String ClientNotes;
  String empEvaluation;
  String rate;
  String empName;
  String sendNote;
  String AdminNotes;
  String WriteYourNotes;
  String Contract;
  String Landscaping;
  String Cost;
  String Warranty;
  String Traps;
  String Report;
  String Location;
  String ReceiptVoucher;
  String Invoice;
  String OfficerNotes;
  String WriteNotes;
  String SendNotes;
  String Profile;
  String Settings;
  String EditProfile;
  String ChangePassword;
  String Notification;
  String Language;
  String ChangeUserName;
  String ChangePhoneNumber;
  String ChangeLocation ;
  String Cancel ;
  String Change ;
  String OldPassword;
  String NewPassword;
  String ConfirmNewPassword ;
  String notificationOffS ;
  String NotificationON ;
  String NotificationOff ;
  String changeDataSuccess;
  String changeImageSuccess;
  String ok;
  String alerterror;
  String alertWrongChange;
  String Passwordliss6;
  String filterBy;
  String complete;
  String workingOn;
  String cancel;
  String status;
  String problem;
  String Products;
  String Product;
  String ExchangePoint;
  String points;
  String JD;
  String ProductPrice;
  String Quantity;
 String terms;
 String sendDone;
 String wrongEmailOrPassword;
 String accNotActive;
 String outOfTime;
 String FillUserNameData;
 String FillPhoneNumberData;
 String FillLocation;
 String FillNameEmp;
 String notes;
 String Title;
 String FillEmail;
 String FillContract;
 String NoProduct;
 String NoCategory;
 String NoServices;
 String NoNotification;
 String SignUpAsEmployee;
 String SignUpAsClient;
 String errorphone;
 String phonenumvalid;
 String ClientAccountcreated;
 String EmpAccountcreated;
 String Note;
 String ChooseServices;
 String DeleteImage;
 String notSend;
 String bad;
 String good;
 String verygood;
 String Excellent;
 String veryExcellent;
 String ClientName;
 String problemName;
 String itemsuccessfullyadd;

 String getStarted;
 String Skip;
 String ForgotPassword;
 String GetANewPassword;
 String checkYourEmail;
 String sendPassword;
String sendProduct;
String sendProductinfo;
String alertDoneChange;
String selectProduct;
String SearchByDate;
String EmployeePage;
String ClientWindow;
String sendNoteSuccessfully;
String sendAppointment;
String Date;
String SendLocation;
String changeEmail;
String confirm;
String GetinTouch;
String ContactUs;
String GetTouchmessage;
String orderhistory;
String changelanguage;
String more;
String category;
String cart;
String createANewAccount;
String registration;
String enterYourEmail;
String forgotYourPassword;
String agree;
String privacyPolicy;
String enterFullName;
String EnteryourPhone;
String pleaseEnterYourName;
String pleaseEnterRealName;
String pleaseEnterYourEmail;
String enterValedEmail;
String mustAgree;
String price;
String available;
String outOfStock;
String inStock;
String productName;
String maximumAvailableStock;
String selectQuantity;
String KD;
String details;
String addToCart;
String delete;
String ConfirmPhoneNumber;
String shoppingCart;
String pleaseLogin;
String addAddress;
String addressName;
String ParcelStreet;
String city;
String Area;
String Building;
String save;
String Addresses;
String add;
String countryName;
String Edit;
String Dear;
String smsText;
String Verification;
String ReSend;
 String EnterTheCode;
 String Next;
 String DidntgettheCode;
 String pleaseFilltheData;
 String EditYourAddress;
 String Homedelivery;
 String CheckYourAddress;
 String DeliveryMethod;
 String Step1;
 String DeliveryDate;
 String Step2;
 String ChooseDate;
 String PleaseCheckPassword;
 String PleaseTypeYourOldPassword;
 String previousOrders;
 String Favorite;
 String PromoCode;
 String EnterPromoCode;
 String Continue;
 String Step4;
 String PricebeforeDiscount;
 String PriceAfterDiscount;
 String AddComment;
 String GetInTouchParagraph;
 String message;
 String name;
 String CurrantEmail;
 String orderDetails;
 String smsCodeAccount;
 String price_unit;
 String totalprice_unit;
 String totalQty_unit;
 String MarklocationMap;
 String orderNumber;
 String paymentType;
 String TotalPrice;
 String AddRating;
 String PurchaseScreen;
 String Step3;
 String confirmOrder;
 String Step5;
 String discountSuccess;
 String DiscountFailed;
 String Nodiscount;
 String orderConfirmDetails;
 String SearchAboutProduct;
 String TotalSummation;
 String showAll;

}

class EnglishString extends Strings {
  EnglishString() {
    appName = 'Al Hud hud';
    langPage = 'Language';
    arabicLang = 'العربية';
    englishLang = 'English';
    languages = 'عربي';
    languagesDes = 'Language';
    alertExitTitle='Alert Exit';
    exitApp='Do you want to exit an App ';
    home='Home';
    AddComment='Add your Comment';
    schedule='Schedule';
    AddRating='Add a Rating';
    profile='My Account';
    product='Products';
    services='Services';
    serviceNoti='Service:';
    selectServices='Select Services';
    servicesDetails='Service Details';
    contract='Contract';
    notification='Notification';
    news='News';
    municipalCouncils='Municipal Councils';
    theMedia='The Media';
    about='About Us';
    contactUs='Contact Us';
    complaintsAndSuggestions='Complaints And Suggestions';
     logout='Logout';
     login='Login';
    KuwaitiLivestock='Kuwaiti Livestock';
    orderConfirmDetails='Your Order has been confirmed successfully';
    userName='User Name';
    fillDataError = 'Please Fill your Data';
    errorUserName='User name can\'t be empty';
    userPassword='Password';
    errorPassword = 'Password can\'t be empty';
    signIn = 'SignIn';
    signInWithFacebook = 'sign In With Facebook';
    dontHaveAccount = 'Don\'t Have a Account ?';
    register = 'Register';
    alreadyHaveAccount = 'Already Have an Account ?';
    signUp = 'SignUp';
    firstUserName = 'First Name';
    lastUserName = 'Last Name';
    phoneNum='Phone Number ';
    massagesDesc='Messages ';
    email='Email';
    userRePassword = 'Retype Password';
    forgetPassword = 'Forgot Password ? ';
    passwordLess6 ='Must more 6 character';
    errorMatchPassword = 'Password must Match !';
    errorPhone='Phone Number can\'t be empty ';
    phoneNumValid='mobile number must be valid';
    alertLogout='Alert Logout';
    exitapp='Do you want to logout an App ';
    emailUsed='email already used';
    send='Send';
      FirstName = 'First Name';
    secondname = 'Second Name';
     photoAlbum = 'Photo Album';
    videoAlbum = 'Video Album';
    MunicipalCouncils = 'Municipal Councils';
    CurrentCouncils = 'Current Councils';
    PreviousCouncils = 'Previous Councils';
    MunicipalMembers = 'Municipal Members';
    employees = 'Employees';
    yes = 'Yes';
    no = 'No';
    ReadMore = 'Read More';
    search = 'Search';
    Nodiscount = 'No discount';
    enterusername = 'Please Enter Email or Phone Number  ';
    enterpassword = 'Please Enter Password';
     welcome = 'Welcome to Al-Hudhud';
     yourMsg = 'Your Message';
    title = 'Title';
    ComplaintTitle = 'If You Have Any Suggestion Or Complaints,Lets Us Know .';
    userEmail = 'Email';
    PleaseWait='Please Wait';
    addAppointment='Add Appointment';
    location='Location';
    locationClient='Client Location';
    uploadImage='Upload Image';
    yourProblem='Your Problem';
    yourNote='Your Note';
     Appointment='Appointment';
    ClientNotes='Add Client Notes';
    empEvaluation ='Employee Evaluation';
    rate ='Your Rate';
    empName ='Officer Name ';
    sendNote ='send Note ';
    AdminNotes='Admin Notes';
    WriteYourNotes='Write Your Notes';
    Contract='Contract';
    Landscaping='Landscaping';
    Cost='Cost';
    Warranty='Warranty';
    Traps='Traps';
    Report='Report';
    ConfirmPhoneNumber='Confirm Phone Number';
    Location='Location';
    ReceiptVoucher='Receipt Voucher';
    Invoice='Invoice';
    OfficerNotes='OfficerNotes';
    WriteNotes='Write Your Notes';
    SendNotes='Send Notes';
    Profile='Profile';
    Settings='Settings';
    EditProfile='Edit Profile';
    ChangePassword='Change Password';
    Notification='Notification';
    Language='Language';
    ChangeUserName='Change Full Name';
    ChangePhoneNumber='Change Phone Number';
    ChangeLocation='Change Your Location: Country/city/area';
    Cancel='Cancel';
    Change='Save Changes';
    OldPassword='Old Password';
    NewPassword ='New Password';
    ConfirmNewPassword ='Confirm New Password';
    notificationOffS ='You\'ve disabled the notifications';
    NotificationON ='Notification ON';
    NotificationOff ='Notification Off';
    changeDataSuccess ='The data has been modified successfully';
    changeImageSuccess ='The Image has been modified successfully';
    ok='ok';
    alerterror='Attention';
    alertWrongChange='It is not modified password. Please be sure to write a new password';
    Passwordliss6='Password less than 6 characters';
    filterBy='Filter By';
    complete='Finished';
    workingOn='Working On';
    cancel='Canceled';
    status='Status';
    problem='Problem';
    Products='Products';
    Product='Product Information';
    ExchangePoint='Exchange Point';
    points='Point';
    JD='JD';
    ProductPrice='Product Price';
    Quantity='Quantity';
    terms = 'Terms and Conditions';
    sendDone = 'Send Successfully';
    wrongEmailOrPassword = 'Invalid Email Or Password !';
    accNotActive = 'Your account is not active ';
    outOfTime = 'The current time is outside the actual working hours';
    FillUserNameData='Please write  user name';
    FillPhoneNumberData='Please write  Your Phone Number';
    FillLocation='Please write  Your Location';
    FillNameEmp='Please write Employee Name';
    notes='Write your notes';
    FillEmail='Write your Email';
    Title='write the complaint/Notes Title';
    FillContract='Please write Contract';
    NoProduct='No Products';
    NoCategory='No Category';
    NoServices='No Services';
    NoNotification='No Notification';
    SignUpAsEmployee='SignIn As Employee';
    SignUpAsClient='SignIn As Client';
    errorphone='Add Mobile Number';
    phonenumvalid='Invalid mobile number';
    ClientAccountcreated='Your account has been successfully created as a customer';
    EmpAccountcreated='Your account has been successfully created as a Employee';
    Note='Note';
    ChooseServices='Please Choose One or more from the Services That you want';
    DeleteImage='Delete Image';
    notSend='Not sent';
    bad='bad';
    good='good';
    DiscountFailed='Discount Failed';
    verygood='very good';
    Excellent='Excellent';
    veryExcellent='Excellent';
    ClientName='Client Name';
    problemName='Problem Name';
    getStarted='Get Started';
    Skip='Skip';
    ForgotPassword='Write e-mail and we will send to you a new password';
    GetANewPassword=' Get A New Password';
    checkYourEmail='Check Your Email';
    sendPassword='We have sent a message containing the password to your email';
    sendProduct='Your order has been sent successfully';
    sendProductinfo='We will contact with you to determine the date of receipt of the order';
    alertDoneChange = 'Password changed successfully';
    selectProduct='Choose the quantity';
    SearchByDate='Search By Date';
    EmployeePage='Employee Window';
    ClientWindow='Client Window';
    sendNoteSuccessfully='Feedback has been sent successfully';
    sendAppointment='The appointment was sent successfully. We will contact you';
    Date='Date:';
    SendLocation='Send Location:';
    changeEmail='change your Email';
    confirm='Confirm';
    GetinTouch='Get in Touch';
    ContactUs='Contact Us';
    GetTouchmessage='message';
    orderhistory='Previous order';
    changelanguage='Change language';
    more='More';
    category='Category';
    cart='cart';
    createANewAccount='Create A New Account?';
    registration='Registration';
    enterYourEmail='Enter Your Email';
    forgotYourPassword='Forgot your password?';
    agree='I have read and agree';
    privacyPolicy='privacy Policy';
    enterFullName='Enter Full Name';
    EnteryourPhone='Enter your Phone';
    pleaseEnterYourName='Please Enter Your Name';
    pleaseEnterRealName='Please Enter Real Name';
    pleaseEnterYourEmail='Please Enter Real Email';
    enterValedEmail='Enter Valid Email';
    mustAgree='must agree to the privacy policy';
    price ='Price :';
    available ='Available :';
    outOfStock ='Out Of Stock';
    inStock='in Stock';
    productName='Product Name';
    maximumAvailableStock='maximum quantity in order :';
    selectQuantity='Select Quantity :';
    KD='KD';
    details='Details';
    addToCart='ADD TO CART';
    delete='Delete';
    shoppingCart='Shopping Cart';
    addAddress=' address';
    pleaseLogin='Please login to be able to complete the purchase';
    addressName='Name of address';
    ParcelStreet='Parcel / Street';
    city='City name';
    Area='Area';
    Building='Building';
    save='Save';
    Addresses='Addresses';
    add='Add';
    Edit='Edit';
    countryName='Country Name';
    Dear='Dear';
    smsText='smsText';
    Verification='Verification';
    message='A text Message with a 6-digit verification Code was just send to your number';
    EnterTheCode='Enter The Code';
    Next='Next';
    DidntgettheCode='Didn\'t get the Code?';
    ReSend='ReSend';
    pleaseFilltheData='please Fill the Data';
    EditYourAddress='Edit Your Address';
    Homedelivery='Home delivery';
    CheckYourAddress='Check Your Address';
    DeliveryMethod='Delivery Method';
    Step1='Step 1';
    DeliveryDate='Delivery Date';
    Step2='Step 2';
    ChooseDate='Choose Date';
    PleaseCheckPassword='Please Check Password';
    PleaseTypeYourOldPassword='Please Type Your Old Password';
    previousOrders='Orders History';
    Favorite='Favorite';
    PromoCode='Promo Code';
    EnterPromoCode='Enter Promo Code';
    Continue='Continue';
    Step4='Step 4';
    name='name';
    CurrantEmail='Currant Email';
    PricebeforeDiscount='Price Before Discount:';
    PriceAfterDiscount='Price After Discount:';
    GetInTouchParagraph='We always wanted to bring you the best service possible, let us know how we can improve it';
    smsCodeAccount='Please enter the code that was sent to you in SMS';
    price_unit='unit price ';
    totalprice_unit='total unit price ';
    totalQty_unit='total unit quantity  ';
    MarklocationMap='Mark the location on the map  ';
    orderNumber='order Number  ';
    paymentType='Payment Type';
    TotalPrice='Total Price for order ';
    PurchaseScreen='Purchase Screen ';
    Step3='Step 3';
    confirmOrder='Confirm Order';
    Step5='Step 5';
    discountSuccess='Discount has been successful';
    orderDetails='Order Details';
    itemsuccessfullyadd='meet item successfully add To your cart';
    SearchAboutProduct='Search About Product';
    TotalSummation='Total Summation';
    showAll='show All';
  }
}

class ArabicString extends Strings {
  ArabicString() {
    appName = 'الهدهد';
    langPage = 'اللغة ';
    arabicLang = 'العربية';
    englishLang = 'English';
    languages = 'English';
    languagesDes = 'اللغة';
    alertExitTitle='تنبيه الخروج';
    exitApp = 'هل تريد الخروج من التطبيق';
    home = 'الرئيسية';
    schedule = 'جدول المواعيد';
    profile = 'حسابي';
    product = 'منتجات';
    Nodiscount = 'لا يوجد خصم';
    services = 'الخدمات';
    serviceNoti = 'الخدمة:';
    selectServices = 'حدد الخدمات';
    servicesDetails = 'تفاصيل الخدمة';
    contract = 'اتفافية';
    notification = 'الإشعارات';
    news = 'الأخبار';
    municipalCouncils = 'مجالس البلدية';
    theMedia = 'وسائل الاعلام';
    about = 'من نحن';
    contactUs = 'تواصل معنا';
    complaintsAndSuggestions = 'شكاوي وإقتراحات';
     logout = 'تسجيل خروج';
    login='تسجيل الدخول';
    userName='إسم المستخدم';
    fillDataError = 'يرجى إدخال بياناتك';
    errorUserName='يرجى إدخال إسم المستخدم';
    userPassword = 'كلمة السر';
    errorPassword = 'يرجى إدخال كلمة السر';
    signIn = 'تسجيل الدخول';
    signInWithFacebook = 'الدخول باستخدام الفيسبوك';
    dontHaveAccount = 'لا يوجد لديك حساب ؟';
    register = 'إنشاء حساب';
    alreadyHaveAccount = 'هل لديك حساب ؟';
    signUp = 'إنشاء حساب';
    firstUserName = 'الإسم الأول';
    lastUserName = 'الإسم الأخير';
    phoneNum = 'رقم الهاتف';
    email = 'البريد الإلكتروني';
    userRePassword = 'تأكيد كلمة السر';
    forgetPassword = ' هل نسيت كلمة السر ؟';
    passwordLess6='يجب ان يكون اكثر من 6 احرف';
    errorMatchPassword = 'يجب تطابق كلمتي السر !';
    errorPhone = 'الرجاء إدخال رقم الهاتف ';
    phoneNumValid='يجب ان يكون رقم الجوال صحيح';
    send='إرسال';
    alertLogout='تنبيه تسجيل الخروج ';
    exitapp = 'هل تريد تسجيل الخروج من التطبيق';
    emailUsed = 'البريد الإلكتروني مستخدم بالفعل';
    FirstName = 'الاسم الاول ';
    userEmail = 'البريد الإلكتروني ';
    welcome = 'مرحبا بكم في الهدهد ';
    yourMsg = 'رسالتك ';
    title = 'العنوان ';
    ComplaintTitle='إذا كان لديك أي اقتراح أو شكاوى ، فأخبرنا بذلك. ';
    addAppointment='أضف موعد';
    location='موقعك ';
    locationClient='موقع العميل';
    uploadImage='  تحميل صورة ';
    yourProblem='مشكلتك ! ';
    yourNote='ملاحظتك ';
    Appointment='المواعيد';
    ClientNotes='إضافة ملاحظات العميل ';
    empEvaluation='تقييم الموظف';
    rate=' تقييمك';
    empName=' اسم الموظف ';
    sendNote=' إرسال ملاحظة ';
    enterpassword='الرجاء إدخال كلمة المرور';
    AdminNotes='ملاحظات الادمن ';
    WriteYourNotes=' أكتب ملاحظاتك ';
    Contract='نوع العقد ';
    Landscaping='تنسيق حدائق ';
    Cost='التكلفة';
    Warranty='الضمان';
    Traps='عفش';
    Report='التقارير';
    Location='الموقع';
    ReceiptVoucher='سند القبض';
    Invoice='فاتورة';
    OfficerNotes='ملاحظات الموظف';
    WriteNotes='أكتب ملاحظاتك';
    SendNotes='ارسال الملاحظات';
    Profile='الملف الشخصي';
    Settings='الإعدادات';
    EditProfile='تعديل الملف الشخصي';
    ChangePassword=' كلمة المرور ';
    Notification='الإشعارات';
    Language='تعديل اللغة';
    ChangeUserName='تعديل الإسم الكامل';
    ChangePhoneNumber='تعديل رقم الجوال ';
    ChangeLocation='تعديل موقعك: البلد/المدينة/المنطقة ';
    Cancel='إلغاء';
    Change='حفظ التغييرات';
    OldPassword='كلمة المرور القديمة';
    NewPassword='كلمة المرور الجديدة';
    ConfirmNewPassword='تأكيد كلمة المرور';
    ConfirmNewPassword='تأكيد كلمة المرور';
    notificationOffS='لقد قمت بتعطيل الإشعارات';
    NotificationON='تفعيل الإشعارات';
    NotificationOff='تعطيل الإشعارات';
    changeDataSuccess='تم تعديل البيانات بنجاح';
    changeImageSuccess='تم تعديل الصورة الشخصية بنجاح';
    ok='موافق';
    alerterror='تنبيه' ;
    alertWrongChange='لم يتم تعديل كلمة المرور. الرجاء التأكد من كتابة كلمة مرور جديدة' ;
    Passwordliss6='كلمة المرور أقل من 6 احرف';
    filterBy='تصفية حسب';
    complete='تم انهاء العمل';
    workingOn='جاري العمل عليه ';
    cancel='ألغيت';
    status='الحالة';
    problem='المشكلة';
    Products='المنتجات';
    Product='معلومات المنتج';
    ExchangePoint='التبديل بالنقاط';
    points='النقاط';
    JD='د.ا';
    ProductPrice='سعر المنتج';
    ReadMore='اقرأ أكثر';
    Quantity='الكمية';
    terms = 'الشروط و الأحكام';
    sendDone = 'تم الإرسال بنجاح';
    wrongEmailOrPassword = 'البريد الالكتروني او كلمة السر غير صحيحة !';
    accNotActive = 'حسابك غير فعال';
    outOfTime = 'الوقت الحالي خارج اوقات الدوام الفعلي';
    FillUserNameData='الرجاء ادخال اسم المستخدم';
    FillPhoneNumberData='الرجاء إدخال رقم الجوال';
    FillLocation='الرجاء إدخال موقعك';
    FillNameEmp='الرجاء كتابة إسم الموظف';
    notes='اكتب ملاحظاتك';
    Title='أكتب عنوان ملاحظاتك أو المشكلة ';
    FillEmail='الرجاء كتابة البريد الالكتروني';
    FillContract='الرجاء إضافة الإتفاقية';
    NoProduct='لا يوجد منتجات';
    PleaseWait='الرجاء الإنتظار';
    NoCategory='لا يوجد تصنيفات';
    NoServices='لا توجد خدمات';
    NoNotification='لا توجد إشعارات';
    SignUpAsEmployee='الدخول كموظف';
    SignUpAsClient='الدخول كمستخدم';
    errorphone='أضف رقم الجوال ';
    phonenumvalid='رقم جوال غير صحيح';
    ClientAccountcreated='تم انشاء حسابك بنجاح قم بتسجيل الدخول';
    Note='ملاحظة';
    ChooseServices='الرجاء إختيار واحدة او أكثر من الخدمات التي تريدها';
    DeleteImage='حذف الصورة';
    notSend='لم يتم الارسال';
    bad='سيء';
    good='جيد';
    verygood='جيد جدا';
    Excellent='ممتاز';
    veryExcellent='ممتاز جدا ';
    ClientName='إسم العميل';
    problemName='إسم المشكلة';
    getStarted='إبدأ الآن';
    Skip='تخطي';
    ForgotPassword='أكتب البريدالإلكتروني وسنرسل لك كلمة مرور جديدة';
    GetANewPassword='احصل على كلمة سر جديدة';
    checkYourEmail='تفحص البريد الالكتروني ';
    sendPassword='لقد قمنا بإرسال رسالة تحتوي على كلمة المرور الى بريدك الالكتروني ';
    sendProduct='تم ارسال طلبك بنجاح ';
    sendProductinfo='سوف نتواصل معك لتحديد موعد استلام الطلب';
    alertDoneChange = 'تم تغيير كلمة السر بنجاح';
    selectProduct='إختر الكمية';
    SearchByDate='البحث حسب التاريخ';
    yes = 'نعم';
    no = 'لا';
    Edit = 'تعديل';
    EmployeePage = 'شاشة الموظف';
    ClientWindow = 'شاشة المستخدم';
    sendNoteSuccessfully='تم ارسال الملاحظات بنجاح';
    EmpAccountcreated='تم إنشاء حسابك كموظف بنجاح ';
    sendAppointment='تم ارسال الموعد بنجاح سنقوم بالتواصل معك';
    Date='التاريخ:';
    SendLocation='إرسال الموقع';
    changeEmail='تعديل البريد الالكتروني';
    confirm='تأكيد';
    GetinTouch='ابقى على تواصل';
    ContactUs='تواصل معنا';
    GetTouchmessage='الرسالة';
    orderhistory='سجل الطلبات ';
    changelanguage='تغيير اللغة';
    more='المزيد';
    category='الفئات';
    cart='سلة المشتريات';
    createANewAccount='انشاء حساب جديد ؟';
    registration='تسجيل';
    enterYourEmail='أدخل بريدك الإلكتروني';
    forgotYourPassword='هل نسيت كلمة السر؟';
    agree='لقد قرأت وأوافق على ';
    privacyPolicy='سياسة الخصوصية';
    enterFullName='أدخل الاسم الكامل';
    EnteryourPhone='أدخل رقم هاتفك';
    pleaseEnterYourName='الرجاء إدخال الإسم';
    pleaseEnterRealName='الرجاء إدخال إسم حقيقي';
    pleaseEnterYourEmail='الرجاء إدخال البريد الالكتروني';
    enterValedEmail='الرجاء إدخال بريد الكاتروني صالح';
    mustAgree='يجب الموافقه على سياسة الخصوصية';
    price ='السعر :';
    available ='متوفر';
    outOfStock ='إنتهى من المخزن';
    inStock ='متوفر';
    productName ='إسم المنتج';
    maximumAvailableStock='أقصى كمية في الطلب ';
    selectQuantity='اختر الكمية';
    KD='دينار كويتي ';
    details='التفاصيل';
    addToCart='أضف إلى السلة';
    delete='حذف';
    shoppingCart='سلة المشتريات';
    addAddress='العنوان';
    pleaseLogin='الرجاء تسجيل الدخول لتتمكن من إتمام عملية الشراء';
    ParcelStreet='قطعة / شارع';
    addressName='إٍسم العنوان';
    city='إٍسم المدينة';
    Area='المنطقة';
    Building='المبنى';
    save='حفظ';
    Addresses='العناوين';
    add='إضافة';
    countryName='إسم الدولة';
    Dear='عزيزي';
    smsText='smsText';
    Verification='التحقق';
    message='تم إرسال رسالة نصية تحتوي على رمز تحقق مكون من 6 أرقام إلى رقمك للتو';
    EnterTheCode='أدخل الرمز';
    Next='التالي';
    DidntgettheCode='لم تحصل على الرمز؟';
    ReSend='إعادة الإرسال';
    Dear='عزيزي';
    pleaseFilltheData='يرجى ملء البيانات';
    EditYourAddress='تعديل العنوان';
    Homedelivery='توصيل منزلي';
    CheckYourAddress='تأكيد العنوان';
    DeliveryMethod='طريقة التوصيل';
    Step1='الخطوة 1';
    DeliveryDate='تاريخ التوصيل';
    Step2='الخطوة 2';
    ChooseDate='إختار تاريخ التوصيل ';
    PleaseCheckPassword='الرجاء التحقق من كلمة المرور';
    PleaseTypeYourOldPassword="الرجاء كتابة كلمة المرور القديمة";
    previousOrders="سجل الطلبات ";
    Favorite="المفضلة";
    PromoCode="كود الخصم";
    EnterPromoCode="أدخل كود الخصم";
    Continue="متابعة";
    Step4="الخطوة 4";
    PricebeforeDiscount="السعر قبل الخصم:";
    PriceAfterDiscount="السعر بعد الخصم:";
    AddComment="أضف تعليقك ";
    GetInTouchParagraph="نريد دائمًا أن نقدم لك أفضل خدمة ممكنة ، دعنا نعرف كيف يمكننا تحسينها ";
    name='الإسم';
    price_unit='سعر الوحدة';
    CurrantEmail='الإيميل الموجود حاليا';
    smsCodeAccount='الرجاء ادخال الرمز الذي تم ارساله لك في رساله نصية ';
    totalprice_unit='إجمالي سعر للمنتج ';
    totalQty_unit='مجموع الكمية للمنتج ';
    MarklocationMap='إختر الموقع على الخارطة';
    orderNumber='رقم الطلب';
    paymentType='طريقة الدفع ';
    TotalPrice='إجمالي السعر لجميع المنتجات ';
    AddRating='أضف تقييمك ';
    PurchaseScreen='شاشة الشراء ';
    Step3='الخطوة 3';
    confirmOrder='تأكيد الطلب ';
    Step5='الخطوة 5';
    discountSuccess=' تم الخصم بنجاح ';
    DiscountFailed=' فشل الخصم';
    orderConfirmDetails=' تم تأكيد الطلب بنجاح ';
    ConfirmPhoneNumber=' تأكيد رقم الجوال ';
    orderDetails=' تفاصيل الطلب';
    KuwaitiLivestock='الكويتية للمواشي';
    itemsuccessfullyadd='تم إضافة المنتج بنجاح الى عربة التسوق ';
    SearchAboutProduct='البحث عن منتج معين ';
    TotalSummation='المجموع الكلي';
    showAll='إظهار الكل';

  }
}
